# This rule is not used by the project my-mysql-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over database.mycompany.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: my-mysql-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysql-admin-role
rules:
- apiGroups:
  - database.mycompany.com
  resources:
  - mysqls
  verbs:
  - '*'
- apiGroups:
  - database.mycompany.com
  resources:
  - mysqls/status
  verbs:
  - get
