apiVersion: database.mycompany.com/v1alpha1
kind: MySQL
metadata:
  labels:
    app.kubernetes.io/name: my-mysql-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysql-sample
spec:
  # TODO(user): Add fields here
